context:
  name: roctracer
  version: "7.0.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: "https://github.com/ROCm/roctracer/archive/refs/tags/rocm-${{ version }}.tar.gz"
    sha256: c9dc54fc8b68a7598b3e9453f7962a87cb02e86d64e5681452ebafd62fb85e96
    patches:
      - disable_tests.patch
      - disable_werror.patch
      - skip_anon_struct_codegen.patch

build:
  number: 0
  skip: not linux

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
  host:
    - rocm-core ${{ version }}.*
    - hipcc ${{ version }}.*
    - cppheaderparser
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}


tests:
  - package_contents:
      include:
        - roctracer/roctracer.h
      lib:
        - roctracer64
        - roctx64
about:
  homepage: https://rocm.docs.amd.com/projects/roctracer
  repository: https://github.com/ROCm/rocm-systems
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "AMD ROCTRACER library"

extra:
  recipe-maintainers:
    - traversaro
