context:
  name: rocfft
  version: "7.0.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: "https://github.com/ROCm/rocFFT/archive/refs/tags/rocm-${{ version }}.tar.gz"
    sha256: 9500c514cb272f09cba9bea74eaac9873e8a8afc1ed30e9f5b87f795d4eda877

build:
  number: 0
  skip: not linux

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
  host:
    - rocm-core ${{ version }}.*
    - rocm-cmake
    - hip-devel
    - hipcc
    - sqlite
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}

tests:
  # Needs hip-devel
  #- requirements:
  #    run:
  #      - cmake-package-check
  #      - ${{ compiler('c') }}
  #      - ${{ compiler('cxx') }}
  #  script:
  #    - cmake-package-check rocfft
  - package_contents:
      include:
        - rocfft/rocfft.h
      lib:
        - rocfft

about:
  homepage: https://rocm.docs.amd.com/projects/rocFFT
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: "rocFFT library."

extra:
  recipe-maintainers:
    - traversaro
