context:
  name: rocfft
  version: "7.0.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: "https://github.com/ROCm/rocFFT/archive/refs/tags/rocm-${{ version }}.tar.gz"
    sha256: 05ccbdcb9d2860c72ff9665670aac44286aaaeabd4fb4e9530e7f4f1b5b01c71

build:
  number: 0
  skip: 
    - not linux
    - hip_compiler_version in (None, "None")

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('hip') }}
    - cmake
    - pkg-config
    - ninja
  host:
    - rocm-core ${{ version }}.*
    - rocm-cmake
    - sqlite
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}

tests:
  # Needs hip-devel
  #- requirements:
  #    run:
  #      - cmake-package-check
  #      - ${{ compiler('c') }}
  #      - ${{ compiler('cxx') }}
  #  script:
  #    - cmake-package-check rocfft
  - package_contents:
      include:
        - rocfft/rocfft.h
      lib:
        - rocfft

about:
  homepage: https://rocm.docs.amd.com/projects/rocFFT
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: "rocFFT library."

extra:
  recipe-maintainers:
    - traversaro
