c_stdlib_version:   # [osx and x86_64]
  - '11.0'          # [osx and x86_64]

blas_impl:
  - mkl        # [(linux and not aarch64) or win]
  - openblas   # [linux and aarch64]
  - accelerate # [osx]

rocm_version:
  - None
  - '7.0' # [linux64]
