c_compiler:
    - clang
cxx_compiler:
    - clangxx
c_compiler_version:
    - 20
cxx_compiler_version:
    - 20

hip_compiler:
    - hip-clang
hip_compiler_version:
    - None
    - '7.0'
rocm_version:
    - None
    - '7.0'

zip_keys:
  -
    - hip_compiler_version
    - rocm_version
