[workspace]
authors = ["Silvio <silvio.traversaro@iit.it>"]
channels = ["https://prefix.dev/conda-forge"]
name = "rocktheconda"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[activation.env]
CONDA_BUILD_ARGS = "-c https://repo.prefix.dev/rock-the-conda -c conda-forge -c local --skip-existing -m ./conda_forge_pinnings/conda_build_config.yaml -m ./recipes/conda_build_config.yaml --output-folder ./output"
RATTLER_BUILD_ARGS = "-c https://repo.prefix.dev/rock-the-conda -c conda-forge --skip-existing=all -m ./conda_forge_pinnings/conda_build_config.yaml -m ./recipes/conda_build_config.yaml "


[tasks]
download-therock-base = "git clone https://github.com/ROCm/TheRock"
download-therock = { cmd = "git submodule update --init ./rocm-systems", cwd = "TheRock", depends-on = ["download-therock-base"] }
extract-deps = "python extract_the_rock_deps.py TheRock"
extract-deps-with-external = "python extract_the_rock_deps.py TheRock --include-external"

# Serialize dependency graph manually to avoid conda-build getting confused and permit to mix conda-build and rattler-build
print-conda-build-args = { cmd = "echo 'CONDA_BUILD_ARGS: '$CONDA_BUILD_ARGS" }
build-rocm-core = { cmd = "rattler-build build $RATTLER_BUILD_ARGS --recipe-dir ./recipes/rocm-core", depends-on = ["print-conda-build-args"]  }
build-rocm-cmake = { cmd = "conda-build $CONDA_BUILD_ARGS ./recipes/rocm-cmake", depends-on = ["build-rocm-core", "print-conda-build-args"]  }
build-rocm-devices-libs = { cmd = "conda-build ./recipes/rocm-device-libs $CONDA_BUILD_ARGS", depends-on = ["build-rocm-core"] }
build-rocm-comgr = { cmd = "conda-build ./recipes/rocm-comgr $CONDA_BUILD_ARGS", depends-on = ["build-rocm-core", "build-rocm-devices-libs"]  }
build-rocr-runtime = { cmd = "conda-build ./recipes/rocr-runtime $CONDA_BUILD_ARGS", depends-on = ["build-rocm-core", "build-rocm-devices-libs"]  }
build-rocminfo = { cmd = "conda-build ./recipes/rocminfo $CONDA_BUILD_ARGS", depends-on = ["build-rocr-runtime", "build-rocm-core"] }
build-hip-no-deps = { cmd = "conda-build ./recipes/hip $CONDA_BUILD_ARGS" }
build-hip = { cmd = "conda-build ./recipes/hip $CONDA_BUILD_ARGS", depends-on = ["build-rocm-core", "build-rocminfo", "build-rocr-runtime", "build-rocm-comgr"] }
build-rocm-smi-no-deps = { cmd = "conda-build ./recipes/rocm-smi $CONDA_BUILD_ARGS"}
build-rocm-smi = { cmd = "conda-build ./recipes/rocm-smi $CONDA_BUILD_ARGS", depends-on = ["build-rocm-core", "build-rocminfo", "build-rocr-runtime"] }
build-all-rattler-build-libraries-no-deps = { cmd = "rattler-build build $RATTLER_BUILD_ARGS --recipe-dir ./recipes"  }
build-all-rattler-build-libraries = { cmd = "rattler-build build $RATTLER_BUILD_ARGS --recipe-dir ./recipes", depends-on = ["build-rocm-core", "build-hip", "build-rocminfo", "build-rocr-runtime", "build-rocm-comgr"] }
build-rocprim = { cmd = "rattler-build build $RATTLER_BUILD_ARGS --recipe-dir ./recipes/rocprim", depends-on = ["build-hip", "build-rocm-core"]  }
build-rocfft = { cmd = "rattler-build build $RATTLER_BUILD_ARGS --recipe-dir ./recipes/rocfft", depends-on = ["build-hip", "build-rocm-core"]  }
build-hipfft = { cmd = "rattler-build build $RATTLER_BUILD_ARGS --recipe-dir ./recipes/hipfft", depends-on = ["build-hip", "build-rocm-core", "build-rocfft"]  }
# This task is used to build all the packages in the packages list that are buildable on a GitHub Action node (so excluding hipblaslt and all the packages that depend on it)
build-packages-lightweight = { cmd = "echo 'Lightweight packages build'", depends-on = ["build-hipfft", "build-rocprim"] }
build-rocblas-no-deps = { cmd = "rattler-build build $RATTLER_BUILD_ARGS --recipe-dir ./recipes/rocblas"  }
build-rocsolver-no-deps = { cmd = "rattler-build build $RATTLER_BUILD_ARGS --recipe-dir ./recipes/rocsolver"  }
build-hipblas-no-deps = { cmd = "rattler-build build $RATTLER_BUILD_ARGS --recipe-dir ./recipes/hipblas"  }
build-llama-no-deps = { cmd = "rattler-build build $RATTLER_BUILD_ARGS --recipe-dir ./recipes/llama.cpp"  }
build-packages = { cmd = "echo 'All packages build'", depends-on = ["build-rocm-core", "build-rocm-cmake", "build-rocm-devices-libs", "build-hip", "build-rocm-smi", "build-all-rattler-build-libraries"] }
clean = "rm -rf feedstocks conda-bld"


# Tasks for building TheRock inside a conda environment with conda compilers
download-therock-all = { cmd = "python ./build_tools/fetch_sources.py", cwd = "TheRock", depends-on = ["download-therock-base"] }
configure-therock = { cmd = "cmake -Bbuild -GNinja . -DTHEROCK_AMDGPU_FAMILIES=gfx110X-dgpu", cwd = "TheRock"}
build-therock = { cmd = "cmake --build build", cwd = "TheRock", depends-on = ["configure-therock"]}

[dependencies]
matplotlib = "*"
networkx = "*"
pydot = "*"
cmake = "*"
cxx-compiler = "*"
graphviz = "*"
pkg-config = "*"

vcs2l = "*"

# commented as it is also a dep from TheRock's requirements.txt, but
# it is also used by our scripts
# pyyaml = "*"


# deps from https://github.com/ROCm/TheRock/blob/3da875b94df9205656c200ff1f47afe0b25afc2b/requirements.txt
pyyaml = "6.0.2.*"

cppheaderparser = ">=2.7.4"
python-build = ">=1.2.2"
meson = ">=1.7.0"
setuptools = ">=80.9.0"

# hipBLASLt deps
joblib = ">=1.4.2"
msgpack-python = ">=1.1.0"

# AWS Redshift connector
redshift_connector = "*"

# Deps for building packages
conda-build = "*"
rattler-build = "*"
conda-forge-pinning = "*"

[target.unix.dependencies]
python-magic = ">=0.4.27"

