[workspace]
authors = ["Silvio <silvio.traversaro@iit.it>"]
channels = ["https://prefix.dev/conda-forge"]
name = "rocktheconda"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[activation.env]
CONDA_BUILD_ARGS = "--skip-existing -m $CONDA_PREFIX/conda_build_config.yaml -m ./recipes/conda_build_config.yaml"

[tasks]
download-therock-base = "git clone https://github.com/ROCm/TheRock"
download-therock = { cmd = "git submodule update --init ./rocm-systems", cwd = "TheRock", depends-on = ["download-therock-base"] }
extract-deps = "python extract_the_rock_deps.py TheRock"
extract-deps-with-external = "python extract_the_rock_deps.py TheRock --include-external"

# Serialize dependency graph manually to avoid conda-build getting confused and permit to mix conda-build and rattler-build
print-conda-build-args = { cmd = "echo 'CONDA_BUILD_ARGS: '$CONDA_BUILD_ARGS" }
build-rocm-cmake = { cmd = "conda-build ./recipes/rocm-cmake $CONDA_BUILD_ARGS", depends-on = ["print-conda-build-args"]  }
build-rocm-devices-libs = { cmd = "conda-build -./recipes/rocm-devices-libs $CONDA_BUILD_ARGS" }
build-rocm-comgr = { cmd = "conda-build ./recipes/rocm-comgr $CONDA_BUILD_ARGS" }
build-rocr-runtime = { cmd = "conda-build ./recipes/rocr-runtime $CONDA_BUILD_ARGS" }
build-rocminfo = { cmd = "conda-build ./recipes/rocminfo $CONDA_BUILD_ARGS", depends-on = ["build-rocr-runtime"] }
build-hip = { cmd = "conda-build --skip-existing ./recipes/hip -m ./recipes/conda-forge-pinning/recipe/conda_build_config.yaml", depends-on = ["build-rocminfo", "build-rocr-runtime", "build-rocm-comgr"] }
build-rocm-smi = { cmd = "conda-build --skip-existing ./recipes/rocm-smi -m ./recipes/conda-forge-pinning/recipe/conda_build_config.yaml", depends-on = ["build-rocminfo", "build-rocr-runtime"] }
build-packages = { cmd = "echo 'All packages build'", depends-on = ["build-rocm-cmake", "build-rocm-devices-libs", "build-hip", "build-rocm-smi"] }
cleans = "rm -rf feedstocks conda-bld"
feedstocks-info = "python feedstock_info.py"
feedstocks-status = "python feedstock_info.py status"

# Tasks for building TheRock inside a conda environment with conda compilers
download-therock-all = { cmd = "python ./build_tools/fetch_sources.py", cwd = "TheRock", depends-on = ["download-therock-base"] }
configure-therock = { cmd = "cmake -Bbuild -GNinja . -DTHEROCK_AMDGPU_FAMILIES=gfx110X-dgpu", cwd = "TheRock"}
build-therock = { cmd = "cmake --build build", cwd = "TheRock", depends-on = ["configure-therock"]}

[dependencies]
matplotlib = "*"
networkx = "*"
pydot = "*"
cmake = "*"
cxx-compiler = "*"
graphviz = "*"
pkg-config = "*"

vcs2l = "*"

# commented as it is also a dep from TheRock's requirements.txt, but
# it is also used by our scripts
# pyyaml = "*"


# deps from https://github.com/ROCm/TheRock/blob/3da875b94df9205656c200ff1f47afe0b25afc2b/requirements.txt
pyyaml = "6.0.2.*"

cppheaderparser = ">=2.7.4"
python-build = ">=1.2.2"
meson = ">=1.7.0"
setuptools = ">=80.9.0"

# hipBLASLt deps
joblib = ">=1.4.2"
msgpack-python = ">=1.1.0"

# AWS Redshift connector
redshift_connector = "*"

# Deps for building packages
conda-build = "*"
rattler-build = "*"
conda-forge-pinning = "*"

[target.unix.dependencies]
python-magic = ">=0.4.27"

