context:
  name: rocblas
  version: "7.0.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: "https://github.com/ROCm/rocBLAS/archive/refs/tags/rocm-${{ version }}.tar.gz"
    sha256: 337a77cec31927e484672002d245d3aebf7a67e95658a8477fc593c95cf281fb

build:
  number: 0
  skip: not linux

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
    # Needed by rocm_check_target_ids CMake function
    - lld 20.*
    - clang-tools 20.*
  host:
    - rocm-core ${{ version }}.*
    - rocm-cmake
    - rocm-smi
    - hipcc
    - hip-devel
    - rocm-device-libs 
    - roctracer
    - hipblas-common
    - hipblaslt
    # Needed for tensilite
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - msgpack-cxx
    - libboost-devel
    - msgpack-python
    - joblib
    - pyyaml
    - packaging
    - rocm-smi
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}


tests:
  #- requirements:
  #    run:
  #      - cmake-package-check
  #      - ${{ compiler('c') }}
  #      - ${{ compiler('cxx') }}
  #  script:
  #    - cmake-package-check rocblas
  - package_contents:
      include:
        - rocblas/rocblas.h
      lib:
        - rocblas

about:
  homepage: https://rocm.docs.amd.com/projects/rocBLAS
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: "rocBLAS is the AMD library for BLAS in ROCm. Implemented using the HIP language and optimized for AMD GPUs."

extra:
  recipe-maintainers:
    - traversaro
