context:
  name: rocblas
  version: "7.0.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: "https://github.com/ROCm/rocBLAS/archive/refs/tags/rocm-${{ version }}.tar.gz"
    sha256: 8398cda68242db2386abc9eaf00c3588bb27e2b382e29be2bc5624c2d4ac8a99

build:
  number: 0
  skip: 
    - not linux
    - hip_compiler_version in (None, "None")

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('hip') }}
    - cmake
    - pkg-config
    - ninja
    # Needed for tensilite
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - msgpack-python
    - joblib
    - pyyaml
    - packaging
    # Needed to clone locally tensile and patch it
    - git
    - sed
  host:
    - rocm-core ${{ version }}.*
    - rocm-cmake
    - rocm-smi
    - roctracer
    - hipblas-common
    - hipblaslt
    # Needed for tensilite
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - msgpack-cxx
    - libboost-devel
    - msgpack-python
    - joblib
    - pyyaml
    - packaging
    - rocm-smi
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}


tests:
  #- requirements:
  #    run:
  #      - cmake-package-check
  #      - ${{ compiler('c') }}
  #      - ${{ compiler('cxx') }}
  #  script:
  #    - cmake-package-check rocblas
  - package_contents:
      include:
        - rocblas/rocblas.h
      lib:
        - rocblas

about:
  homepage: https://rocm.docs.amd.com/projects/rocBLAS
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: "rocBLAS is the AMD library for BLAS in ROCm. Implemented using the HIP language and optimized for AMD GPUs."

extra:
  recipe-maintainers:
    - traversaro
