context:
  name: hipblaslt
  version: "7.0.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: "https://github.com/ROCm/hipBLASlt/archive/refs/tags/rocm-${{ version }}.tar.gz"
    sha256: 52d7c1c6852f501f5bd37fa962e6538592741792593a173d8b6963b8f7bd2c41
    patches:
      - fix_latest_msgpack_cxx.patch

build:
  number: 0
  skip: not linux

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    # Workaround for rocroller bug, remove in the future
    - cmake<4
    - pkg-config
    - ninja
  host:
    - rocm-core ${{ version }}.*
    - rocm-cmake ${{ version }}.*
    - hipcc ${{ version }}.*
    - hipblas-common
    - roctracer
    # Needed for tensilite
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - msgpack-cxx
    - libboost-devel
    - msgpack-python
    - joblib
    - pyyaml
    - packaging
    - rocm-smi
    # Needed for rocroller
    - spdlog
    - lld 20.*
    - zlib
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}

tests:
  # Temporary commented out, find_package(hipblaslt) needs
  # hip-devel to be installed to work, but it does not make sense
  # to add that as a run dependency, unless we add a hipblaslt-devel
  # package.
  # - requirements:
  #    run:
  #      - cmake-package-check
  #      - ${{ compiler('c') }}
  #      - ${{ compiler('cxx') }}
  #  script:
  #    - cmake-package-check hipblaslt
  - package_contents:
      include:
        - hipblaslt/hipblaslt.h
      lib:
        - hipblaslt
about:
  homepage: https://rocm.docs.amd.com/projects/hipBLASLt
  repository: https://github.com/ROCm/rocm-libraries
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: "HIP library for GEMM operations with extended functionality"

extra:
  recipe-maintainers:
    - traversaro
