context:
  name: rocm-core
  version: "7.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: "https://github.com/ROCm/rocm-core/archive/refs/tags/rocm-${{ version }}.tar.gz"
    sha256: d7741e12d184a6553f6d39b3ff4d113a2e7eeb509d5ec08e06cdaf51dcd26f90

build:
  number: 0
  skip: not linux

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja

tests:
  - requirements:
      run:
        - cmake-package-check
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
    script:
      - cmake-package-check rocm-core
  - package_contents:
      include:
        - rocm-core/rocm_version.h
      lib:
        - rocm-core

about:
  homepage: https://github.com/ROCm/rocm-core
  license: MIT
  license_family: MIT
  license_file: copyright
  summary: "ROCm core package"

extra:
  recipe-maintainers:
    - traversaro