context:
  name: rocsolver
  version: "7.0.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: "https://github.com/ROCm/rocSOLVER/archive/refs/tags/rocm-${{ version }}.tar.gz"
    sha256: 675c7cdc0e582f93d81d2dcd953ea567f040cbeb300ccd2db61cad4a07ca1d5b

build:
  number: 0
  skip: not linux

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
  host:
    - rocm-core ${{ version }}.*
    - rocm-cmake
    - hipcc
    - rocblas
    - rocprim
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}

tests:
  # needs hip-devel
  #- requirements:
  #    run:
  #      - cmake-package-check
  #      - ${{ compiler('c') }}
  #      - ${{ compiler('cxx') }}
  #  script:
  #    - cmake-package-check ${{ name }}
  - package_contents:
      include:
        - ${{ name }}/${{ name }}.h
      lib:
        - ${{ name }}

about:
  homepage: https://rocm.docs.amd.com/projects/rocSOLVER
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: "AMD ROCm SOLVER library."

extra:
  recipe-maintainers:
    - traversaro