context:
  name: rocsolver
  version: "7.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: "https://github.com/ROCm/rocSOLVER/archive/refs/tags/rocm-${{ version }}.tar.gz"
    sha256: 635bbf625d81e11afc70f6c0e23212ed13ea20ea50cf995d3dfa0e4636c19558

build:
  number: 0
  skip: not linux

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
    # Needed by rocm_check_target_ids CMake function
    - lld 20.*
    - clang-tools 20.*
  host:
    - rocm-core ${{ version }}.*
    - rocm-cmake
    - hipcc
    - hip-devel
    - rocm-device-libs 
    - rocblas
    - rocprim
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}

tests:
  # needs hip-devel
  #- requirements:
  #    run:
  #      - cmake-package-check
  #      - ${{ compiler('c') }}
  #      - ${{ compiler('cxx') }}
  #  script:
  #    - cmake-package-check ${{ name }}
  - package_contents:
      include:
        - ${{ name }}/${{ name }}.h
      lib:
        - ${{ name }}

about:
  homepage: https://rocm.docs.amd.com/projects/rocSOLVER
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: "AMD ROCm SOLVER library."

extra:
  recipe-maintainers:
    - traversaro