context:
  name: hipblas-common
  version: "7.0.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: "https://github.com/ROCm/hipBLAS-common/archive/refs/tags/rocm-${{ version }}.tar.gz"
    sha256: 7b8007784831d895fb0a432f366388bc7d212443a25ea9f14eb2aa0a7b4ad5d7

build:
  number: 0
  skip: not linux

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
  host:
    - rocm-core ${{ version }}.*
    - rocm-cmake ${{ version }}.*


tests:
  - requirements:
      run:
        - cmake-package-check
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
    script:
      - cmake-package-check hipblas-common
  - package_contents:
      include:
        - hipblas-common/hipblas-common.h

about:
  homepage: https://github.com/ROCm/rocm-libraries
  repository: https://github.com/ROCm/rocm-libraries
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: "hipBLAS-common is a header-only library that provides common files for hipBLAS and hipBLASLt."

extra:
  recipe-maintainers:
    - traversaro