context:
  name: hipblas
  version: "7.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: "https://github.com/ROCm/hipBLAS/archive/refs/tags/rocm-${{ version }}.tar.gz"
    sha256: 9500c514cb272f09cba9bea74eaac9873e8a8afc1ed30e9f5b87f795d4eda877

build:
  number: 0
  skip: not linux

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
    # Needed by rocm_check_target_ids CMake function
    - lld 20.*
  host:
    - rocm-core ${{ version }}.*
    - rocm-cmake
    - rocm-smi
    - hipblaslt ${{ version }}.*
    - hipcc
    - hip-devel
    - rocm-device-libs 
    - roctracer
    - hipblas-common
    - rocblas
    - rocsolver

tests:
  # Needs hip-devel
  #- requirements:
  #    run:
  #      - cmake-package-check
  #      - ${{ compiler('c') }}
  #      - ${{ compiler('cxx') }}
  #  script:
  #    - cmake-package-check hipblas
  - package_contents:
      include:
        - hipblas/hipblas.h
      lib:
        - hipblas

about:
  homepage: https://rocm.docs.amd.com/projects/hipBLAS
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: "ROCm BLAS marshalling library."

extra:
  recipe-maintainers:
    - traversaro