context:
  name: hipblas
  version: "7.0.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: "https://github.com/ROCm/hipBLAS/archive/refs/tags/rocm-${{ version }}.tar.gz"
    sha256: af179faab4ff5eec5d5ca3af3640644c72c9a9ca676cfab50591e9d9f3fadf80

build:
  number: 0
  skip: 
    - not linux
    - hip_compiler_version in (None, "None")

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('hip') }}
    # Note: fortran is only required on Linux
    - ${{ compiler('fortran') }}
    - cmake
    - pkg-config
    - ninja
    # Needed by rocm_check_target_ids CMake function
    - lld 20.*
  host:
    - rocm-core ${{ version }}.*
    - rocm-cmake
    - rocm-smi
    - hipblaslt
    - roctracer
    - hipblas-common
    - rocblas
    - rocsolver
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}

tests:
  # Needs hip-devel
  #- requirements:
  #    run:
  #      - cmake-package-check
  #      - ${{ compiler('c') }}
  #      - ${{ compiler('cxx') }}
  #  script:
  #    - cmake-package-check hipblas
  - package_contents:
      include:
        - hipblas/hipblas.h
      lib:
        - hipblas

about:
  homepage: https://rocm.docs.amd.com/projects/hipBLAS
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: "ROCm BLAS marshalling library."

extra:
  recipe-maintainers:
    - traversaro