context:
  name: rocprofiler-sdk
  version: "7.0.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/ROCm/rocprofiler-sdk/archive/refs/tags/rocm-${{ version }}.tar.gz
  sha256: 2f5e9bbddf657b7a78f7cd4afe1984c3a5518af0bc7babace1e3d29dcfcde52a
  patches:
    - 0001-disable-building-submodules.patch
    - 0002-disable-cpackaging.patch
    - 0003-add-ptl-and-elfio-imported-targets.patch
    - 0004-add-missing-headers.patch
    - 0005-ptl-thread-pool-config.patch

build:
  number: 0
  skip:
    - not linux
    - hip_compiler_version in (None, "None")

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('hip') }}
    - cmake
    - ninja
    - python
  host:
    - rocm-core ${{ version }}.*
    - rocr-runtime
    - rocprofiler-register
    - rccl
    - libdrm
    - numactl
    - fmt
    - ptl
    - glog
    - pybind11
    - yaml-cpp
    - cereal
    - nlohmann_json
    - elfio
    - gotcha
    - perfetto
    - tbb-devel

tests:
  - package_contents:
      include:
        - rocprofiler-sdk
      lib:
        - rocprofiler-sdk

about:
  repository: https://github.com/ROCm/rocprofiler-sdk
  homepage: https://rocm.docs.amd.com/projects/rocprofiler-sdk/en/latest/
  license: MIT
  license_file: LICENSE
  summary: "ROCm profiler SDK for GPU profiling and tracing"
  description: |
    ROCprofiler-SDK is AMD's tooling infrastructure providing a hardware-specific
    low-level performance analysis interface for profiling and tracing GPU compute
    applications.

extra:
  recipe-maintainers:
    - flferretti
    - conda-forge/rocm-core
