context:
  name: ptl
  version: "2.3.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/jrmadsen/PTL/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 3275ad8ec2971c89aacb3b922717dc4e774fa4e59fc3f4035053225c802aee52

build:
  number: 0
  skip:
    - not linux

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - tbb-devel
  run_exports:
    - ${{ pin_subpackage(name, upper_bound="x.x") }}
  run_constraints:
    - tbb-devel

tests:
  - package_contents:
      include:
        - PTL/PTL.hh
      lib:
        - ptl

about:
  repository: https://github.com/jrmadsen/PTL
  homepage: https://github.com/jrmadsen/PTL
  license: MIT
  license_file:
    - LICENSE
  summary: "PTL Parallel Tasking Library"
  description: |
    Lightweight C++11 multithreading tasking system featuring thread-pool,
    task-groups, and lock-free task queue.

extra:
  recipe-maintainers:
    - flferretti
    - traversaro
