context:
  name: rocprim
  version: "7.0.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: "https://github.com/ROCm/rocPRIM/archive/refs/tags/rocm-${{ version }}.tar.gz"
    sha256: bde28c7d08b46ba46d9ab13496d0d63353e4eae0e7e884167c10bccc9ebcb933

build:
  number: 0
  skip: not linux

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
  host:
    - rocm-core ${{ version }}.*
    - rocm-cmake
    - hipcc


tests:
  # Temporary commented out, find_package(rocprim) needs
  # hip-devel to be installed to work, but it does not make sense
  # to add that as a run dependency, unless we add a rocprim-devel
  # package.
  # - requirements:
  #    run:
  #      - cmake-package-check
  #      - ${{ compiler('c') }}
  #      - ${{ compiler('cxx') }}
  #  script:
  #    - cmake-package-check rocprim
  - package_contents:
      include:
        - ${{ name }}/${{ name }}.hpp

about:
  homepage: https://rocm.docs.amd.com/projects/rocPRIM
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "rocPRIM is a header-only library that provides HIP parallel primitives."

extra:
  recipe-maintainers:
    - traversaro