context:
  version: "7.0.2"

package:
  name: aqlprofile
  version: ${{ version }}

source:
  url: https://github.com/ROCm/aqlprofile/archive/refs/tags/rocm-${{ version }}.tar.gz
  sha256: 1c56781bf40e7195b1dd670b8f05ecc0b2007c57c0a0b80fea97dfaa9999e8e3

build:
  number: 0
  skip:
    - not linux

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - rocm-core
    - rocr-runtime

about:
  homepage: https://github.com/ROCm/aqlprofile
  license: MIT
  license_file: LICENSE
  summary: AQLPROFILE library for AMD GPU profiling
  description: |
    AQLPROFILE provides AQL packet level profiling support for AMD GPUs.
    It is used by profiling tools to collect hardware performance counters.

extra:
  recipe-maintainers:
    - flferretti
    - conda-forge/rocm-core
