context:
  name: composable-kernel
  version: "7.0.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/ROCm/composable_kernel/archive/refs/tags/rocm-${{ version }}.tar.gz
  sha256: b7293e3451750f606ab845585b3dd4eb4e185d4dda4a22290d73e8874a45a26b

build:
  number: 0
  skip:
    - not linux
    - hip_compiler_version in (None, "None")

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('hip') }}
    - cmake
    - ninja
  host:
    - rocm-core ${{ version }}.*
    - rocm-cmake
  run_exports:
    - ${{ pin_subpackage(name, upper_bound="x.x") }}

tests:
  - package_contents:
      include:
        - ck/library/reference_tensor_operation/cpu/reference_gemm
        - ck/library/reference_tensor_operation/gpu/reference_gemm.hpp
        - ck/library/tensor_operation_instance/gpu/grouped_gemm.hpp
      lib:
        - libdevice_conv_operations.a

about:
  repository: https://github.com/ROCm/composable_kernel
  license: MIT
  license_file: LICENSE
  summary: "Composable Kernel: Performance Portable Programming Model for Machine Learning Tensor Operators"
  description: |
    The Composable Kernel (CK) library provides a programming model for writing
    performance-critical kernels for machine learning workloads across multiple
    architectures (GPUs, CPUs, etc.).

extra:
  recipe-maintainers:
    - flferretti
    - conda-forge/rocm-core
