context:
  name: gotcha
  version: "1.0.8"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/LLNL/GOTCHA/archive/refs/tags/${{ version }}.tar.gz
  sha256: 267ac6d02916863c8a360b192f1f36e4eaeb8945c73ae7f92116d6f801ad8184

build:
  number: 0
  skip:
    - not linux

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
  run_exports:
    - ${{ pin_subpackage(name, upper_bound="x.x") }}

tests:
  - package_contents:
      include:
        - gotcha/gotcha.h
      lib:
        - libgotcha

about:
  repository: https://github.com/LLNL/GOTCHA
  homepage: https://github.com/LLNL/GOTCHA
  license: LGPL-2.0-only
  license_file:
    - LGPL
  summary: "GOTCHA is a library for wrapping function calls in shared libraries."
  description: |
    Gotcha is a library that wraps functions. Tools can use gotcha
    to install hooks into other libraries, for example putting a wrapper
    function around libc's malloc.

extra:
  recipe-maintainers:
    - flferretti
    - traversaro
