context:
  name: perfetto
  version: "53.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/google/perfetto/archive/refs/tags/v${{ version }}.tar.gz
  sha256: b25023f3281165a1a7d7cde9f3ed2dfcfce022ffd727e77f6589951e0ba6af9a

build:
  number: 0
  skip:
    - not linux

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - meson
    - ninja
    - python
    - pkg-config

tests:
  - package_contents:
      lib:
        - libperfetto.a


about:
  repository: https://github.com/google/perfetto
  homepage: https://perfetto.dev
  license: Apache-2.0
  license_file: LICENSE
  summary: "Perfetto - System profiling, tracing, and observability framework"
  description: |
    Perfetto is an open-source project for performance instrumentation and tracing of
    Linux, Android, and Chrome. It provides a comprehensive set of tools and libraries
    to collect, process, and visualize performance data from various sources.

extra:
  recipe-maintainers:
    - flferretti
    - traversaro
