export HIP_PATH=$HIP_PATH_CONDA_BACKUP
unset HIP_PATH_CONDA_BACKUP
if [ -z $HIP_PATH ]; then
    unset HIP_PATH
fi

export HIP_CLANG_PATH=$HIP_CLANG_PATH_CONDA_BACKUP
unset HIP_CLANG_PATH_CONDA_BACKUP
if [ -z $HIP_CLANG_PATH ]; then
    unset HIP_CLANG_PATH
fi

export CONDA_FORGE_DEFAULT_ROCM_GPU_TARGETS=$CONDA_FORGE_DEFAULT_ROCM_GPU_TARGETS_CONDA_BACKUP
unset CONDA_FORGE_DEFAULT_ROCM_GPU_TARGETS_CONDA_BACKUP
if [ -z $CONDA_FORGE_DEFAULT_ROCM_GPU_TARGETS ]; then
    unset CONDA_FORGE_DEFAULT_ROCM_GPU_TARGETS
fi
