export CONDA_FORGE_DEFAULT_ROCM_GPU_TARGETS=$CONDA_FORGE_DEFAULT_ROCM_GPU_TARGETS_CONDA_BACKUP
unset CONDA_FORGE_DEFAULT_ROCM_GPU_TARGETS_CONDA_BACKUP
if [ -z $CONDA_FORGE_DEFAULT_ROCM_GPU_TARGETS ]; then
    unset CONDA_FORGE_DEFAULT_ROCM_GPU_TARGETS
fi

export HIPCXX=$HIPCXX_CONDA_BACKUP
unset HIPCXX_CONDA_BACKUP
if [ -z $HIPCXX ]; then
    unset HIPCXX
fi
