name: Build conda packages

on:
  workflow_dispatch:
  pull_request:
  push:

env:
  # Change to 'true' to ignore cache and force a full rebuild, but please restore to 'false' before merging
  IGNORE_CACHE_AND_DO_FULL_REBUILD: 'true'

jobs:
  build-packages:
    name: '[pixi:build-packages:${{ matrix.os }}]'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            folder_cache: 'output/linux-64'
    steps:
    - uses: actions/checkout@v4

    - name: Set up pixi
      uses: prefix-dev/setup-pixi@v0.9.0

    - name: Print pixi info
      run: pixi info

    - name: Remove local condarc
      run: rm -f $HOME/.condarc

    - name: Restore build cache
      id: cache-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          ${{ matrix.folder_cache }}
        key: ${{ runner.os }}-conda-pkgs-cache
        # allow a later run to pick up a cache that has an extra suffix
        restore-keys: |
          ${{ runner.os }}-conda-pkgs-cache

    - name: Optional force full rebuild
      if: ${{ env.IGNORE_CACHE_AND_DO_FULL_REBUILD == 'true' }}
      shell: bash -l {0}
      run: |
        rm -rf ${{ matrix.folder_cache }}/*

    - name: Build packages
      # We can't build all packages in github actions, because of lack of memory for hipblaslt
      # So we build only the packages that are lightweight enough to be built in a github action
      run: pixi run build-packages-lightweight

    - name: Save build cache
      uses: actions/cache/save@v4
      if: always()
      with:
        path: |
          ${{ matrix.folder_cache }}
        key: ${{ runner.os }}-conda-pkgs-cache-${{ github.run_id }}-${{ github.run_attempt }}