name: Run tests with pixi

on:
  workflow_dispatch:
  pull_request:


jobs:
  pixi-test:
    name: '[pixi:${{ matrix.os }}]'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [
          ubuntu-24.04,
          windows-2022
        ]
    steps:
    - uses: actions/checkout@v4

    - name: Set up pixi
      uses: prefix-dev/setup-pixi@v0.9.0

    - name: Print pixi info
      run: pixi info

    - name: Download the rock
      run: pixi run download-therock-all

    - name: Build deps image
      run: pixi run extract-deps

    - name: Build deps image
      run: pixi run build-therock
