name: Build conda packages

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build-packages:
    name: '[pixi:build-packages:${{ matrix.os }}]'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [
          ubuntu-24.04
        ]
    steps:
    - uses: actions/checkout@v4

    - name: Set up pixi
      uses: prefix-dev/setup-pixi@v0.9.0

    - name: Print pixi info
      run: pixi info

    - name: Remove local condarc
      run: rm -f $HOME/.condarc

    - name: Build packages
      run: pixi run build-packages
